"""
simulate.py

Drives real conversations against the packaged Mnemosyne system for all
10 personas, across multiple sessions each. Persona utterances are
generated by Qwen itself (role-playing the persona's character), so
conversations are varied and natural rather than scripted -- this
produces production-realistic memory writes, not synthetic data.

Each persona runs its sessions sequentially (to keep session/turn
continuity simple and correct); personas run concurrently across each
other (bounded by --concurrency) since they're independent users.

Usage:
    python simulate.py --sessions 20 --turns 3 --concurrency 3

Requires:
    QWEN_API_KEY (and optionally QWEN_BASE_URL / QWEN_MODEL) in your .env,
    same as the main system -- this reuses memory_engine.llm_client.QwenClient
    directly for persona generation, so it's the exact same model/endpoint.

Writes a full transcript log to transcripts.jsonl (one line per turn) in
addition to whatever memory_engine itself writes to the test Mongo/Qdrant
stack, so you have a human-readable record independent of the DB.
"""
from __future__ import annotations

import argparse
import asyncio
import json
import time
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

from memory_engine.client import MnemosyneClient, MnemosyneConfig
from memory_engine.llm_client import QwenClient

from personas import PERSONAS, SESSION_GOALS


def swap_roles(history: list[dict]) -> list[dict]:
    """From the persona-generator's point of view, Mnemosyne's replies are
    what IT responds to (role=user), and the persona's own past lines are
    its own past output (role=assistant)."""
    return [
        {"role": "user" if turn["role"] == "assistant" else "assistant",
         "content": turn["content"]}
        for turn in history
    ]


async def generate_persona_message(
    persona_llm: QwenClient, persona: dict, session_goal: str, history: list[dict],
) -> str:
    system_prompt = (
        f"{persona['character']}\n\n"
        f"Your recurring topics/interests: {', '.join(persona['topics'])}.\n\n"
        f"This conversation's goal: {session_goal}\n\n"
        "Respond as this person would in a real chat -- natural, in "
        "character, 1-3 sentences, no meta-commentary, no describing your "
        "own actions, just the message itself."
    )
    messages = [{"role": "system", "content": system_prompt}]
    messages.extend(swap_roles(history))
    if not history:
        messages.append({"role": "user",
                          "content": "(Start the conversation about one of your topics.)"})
    else:
        messages.append({"role": "user", "content": "(Continue naturally.)"})

    return await persona_llm.chat_raw(messages, max_tokens=150, temperature=0.9)


async def run_persona(
    client: MnemosyneClient, persona_llm: QwenClient, persona: dict,
    n_sessions: int, n_turns: int, transcript_lock: asyncio.Lock, transcript_path: Path,
):
    user_id = persona["user_id"]
    for session_i in range(n_sessions):
        session_id = None
        history: list[dict] = []
        goal = SESSION_GOALS[session_i % len(SESSION_GOALS)]

        for turn_i in range(n_turns):
            persona_msg = await generate_persona_message(persona_llm, persona, goal, history)

            result = await client.turn(
                user_id=user_id, query=persona_msg, session_id=session_id, history=history,
            )
            session_id = result["session_id"]
            history.append({"role": "user", "content": persona_msg})
            history.append({"role": "assistant", "content": result["reply"]})

            record = {
                "user_id": user_id, "session_id": session_id,
                "session_index": session_i, "turn_index": turn_i,
                "query": persona_msg, "reply": result["reply"],
                "written": result["written"], "retrieved": [r.get("memory_id") for r in result["retrieved"]],
                "archived": result["archived"], "ts": time.time(),
            }
            async with transcript_lock:
                with open(transcript_path, "a") as f:
                    f.write(json.dumps(record) + "\n")

        print(f"  [{user_id}] session {session_i + 1}/{n_sessions} done "
              f"({n_turns} turns, session_id={session_id})")


async def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--sessions", type=int, default=20, help="sessions per persona")
    parser.add_argument("--turns", type=int, default=3, help="turns per session")
    parser.add_argument("--concurrency", type=int, default=3, help="personas run concurrently")
    parser.add_argument("--mongo_url", type=str,
                         default="mongodb://agent:agent@localhost:27018/memories?authSource=admin")
    parser.add_argument("--qdrant_url", type=str, default="http://localhost:6334")
    parser.add_argument("--transcript_out", type=str, default="transcripts.jsonl")
    args = parser.parse_args()

    transcript_path = Path(args.transcript_out)
    transcript_path.write_text("")  # fresh file each run

    client = await MnemosyneClient.create(
        MnemosyneConfig(mongo_url=args.mongo_url, qdrant_url=args.qdrant_url)
    )
    persona_llm = QwenClient()  # separate instance, same Qwen endpoint/model

    print(f"Simulating {len(PERSONAS)} personas x {args.sessions} sessions x "
          f"{args.turns} turns (concurrency={args.concurrency})")
    print(f"Target: mongo={args.mongo_url}  qdrant={args.qdrant_url}")
    print(f"⚠ this is the ISOLATED TEST stack, not production, right? double check.\n")

    transcript_lock = asyncio.Lock()
    semaphore = asyncio.Semaphore(args.concurrency)

    async def bounded_run(persona):
        async with semaphore:
            await run_persona(client, persona_llm, persona, args.sessions, args.turns,
                               transcript_lock, transcript_path)

    start = time.time()
    await asyncio.gather(*(bounded_run(p) for p in PERSONAS))
    elapsed = time.time() - start

    print(f"\nDone in {elapsed:.1f}s. Transcript written to {transcript_path}")
    print("Next: run extract_dataset.py to pull memory_engine's Mongo/Qdrant "
          "state into the eval harness's {memories, queries} format.")


if __name__ == "__main__":
    asyncio.run(main())